// src/validators/product.validator.ts
import Joi from "joi";

// Joi schema for ProductVariant
const productVariantSchema = Joi.object({
    size: Joi.string().trim().required().messages({
        'string.empty': 'Variant size is required',
        'any.required': 'Variant size is required'
    }),
    color: Joi.string().trim().required().messages({
        'string.empty': 'Variant color is required',
        'any.required': 'Variant color is required'
    }),
    stock: Joi.number().integer().min(0).default(1).required().messages({
        'number.base': 'Stock must be a number',
        'number.integer': 'Stock must be an integer',
        'number.min': 'Stock cannot be negative',
        'any.required': 'Stock is required'
    }),
    // SKU is auto-generated by the controller
    sku: Joi.forbidden()
});

// Joi schema for ProductReview (for internal use, not typically for client input on product creation)
const productReviewSchema = Joi.object({
    userId: Joi.forbidden(),
    rating: Joi.number().integer().min(1).max(5).required().messages({
        'number.base': 'Rating must be a number',
        'number.integer': 'Rating must be an integer',
        'number.min': 'Rating must be at least 1',
        'number.max': 'Rating cannot exceed 5',
        'any.required': 'Rating is required'
    }),
    comment: Joi.string().trim().required().messages({
        'string.empty': 'Comment cannot be empty',
        'any.required': 'Comment is required'
    }),
    likes: Joi.number().integer().min(0).default(0),
    dislikes: Joi.number().integer().min(0).default(0),
    replies: Joi.array().items(Joi.object({
        userId: Joi.forbidden(),
        comment: Joi.string().trim().required(),
        createdAt: Joi.date().iso().optional() // Optional for input, model will default
    })).optional()
});


// Joi schema for creating a new product
const createProductSchema = Joi.object({
    // PSR is auto-generated by the controller
    psr: Joi.forbidden(),
    title: Joi.string().trim().required().messages({
        'string.empty': 'Product title is required',
        'any.required': 'Product title is required'
    }),
    // Slug is auto-generated by the model's pre-save hook
    slug: Joi.forbidden(),
    images: Joi.array().items(Joi.string().uri().trim().required()).min(1).max(5).required().messages({
        'array.base': 'Images must be an array',
        'array.min': 'At least one image URL is required',
        'any.required': 'Product images are required',
        'string.uri': 'Each image must be a valid URL'
    }),
    brand: Joi.string().trim().required().messages({
        'string.empty': 'Brand is required',
        'any.required': 'Brand is required'
    }),
    category: Joi.array().items(Joi.string().valid('Men', 'Women', 'Accessories', 'Men\'s Accessories', 'Women\'s Accessories').trim()).min(1).required().messages({
        'array.base': 'Category must be an array of strings.',
        'array.min': 'At least one category is required.',
        'any.required': 'Category is required.',
        'any.only': 'Category must be one of [men, women, accessories].'
    }),
    description: Joi.string().trim().max(2000).required().messages({
        'string.empty': 'Description is required',
        'any.required': 'Description is required',
        'string.max': 'Description must not exceed 2000 characters'
    }),
    keyFeatures: Joi.array().items(Joi.string().trim()).min(1).max(10).optional().messages({
        'array.max': 'Maximum of 10 key features allowed'
    }),
    basePrice: Joi.number().min(0).required().messages({
        'number.base': 'Base price must be a number',
        'number.min': 'Base price cannot be negative',
        'any.required': 'Base price is required'
    }),
    // salePrice, discount, onSale, totalStock are calculated by the model's pre-save hook
    salePrice: Joi.number().min(0).optional(),
    discount: Joi.number().min(0).max(100).optional(),
    onSale: Joi.boolean().optional(),
    saleTax: Joi.number().min(0).default(18).optional(),
    totalStock: Joi.number().min(0).optional(),
    variants: Joi.array().items(productVariantSchema).min(1).required().messages({
        'array.base': 'Variants must be an array',
        'array.min': 'At least one product variant is required',
        'any.required': 'Product variants are required'
    }),
    // Reviews, averageRating, totalReviews are not provided on product creation
    reviews: Joi.forbidden(),
    averageRating: Joi.forbidden(),
    onFeatured: Joi.boolean().optional(),
    isActive: Joi.boolean().default(true).optional(),
    relatedProducts: Joi.array().items(Joi.string().hex().length(24)).max(5).optional().messages({
        'array.max': 'Maximum of 5 related products allowed',
        'string.hex': 'Related product IDs must be hexadecimal strings',
        'string.length': 'Related product IDs must be 24 characters long'
    }),
    // Seller is set by the backend based on the authenticated user
    seller: Joi.forbidden(),
    status: Joi.string().valid("approved", "rejected", "pending", "draft", "outOfStock").default("draft").optional()
});

// Joi schema for updating an existing product
const updateProductSchema = Joi.object({
    psr: Joi.forbidden(),
    title: Joi.string().trim().optional(),
    slug: Joi.forbidden(), // Slug should not be updated directly
    images: Joi.array().items(Joi.string().uri().trim()).min(1).max(5).optional().messages({
        'array.min': 'At least one image URL is required'
    }),
    brand: Joi.string().trim().optional(),
    category: Joi.array().items(Joi.string().valid('Men', 'Women', 'Accessories', 'Men\'s Accessories', 'Women\'s Accessories').trim()).min(1).required().messages({
        'array.min': 'At least one category is required.',
        'any.only': 'Category must be one of [men, women, accessories].'
    }),
    description: Joi.string().trim().max(2000).required().messages({
        'string.empty': 'Description is required',
        'any.required': 'Description is required',
        'string.max': 'Description must not exceed 2000 characters'
    }),
    keyFeatures: Joi.array().items(Joi.string().trim()).min(1).max(10).optional().messages({
        'array.max': 'Maximum of 10 key features allowed'
    }),
    basePrice: Joi.number().min(0).optional(),
    salePrice: Joi.number().min(0).optional(),
    discount: Joi.number().min(0).max(100).optional(),
    onSale: Joi.boolean().optional(),
    saleTax: Joi.number().min(0).optional(),
    totalStock: Joi.number().min(0).optional(),
    variants: Joi.array().items(productVariantSchema).min(1).optional().messages({
        'array.min': 'At least one product variant is required'
    }),
    reviews: Joi.array().items(productReviewSchema).optional(),
    averageRating: Joi.number().min(0).max(5).optional(),
    onFeatured: Joi.boolean().optional(),
    isActive: Joi.boolean().optional(),
    relatedProducts: Joi.array().items(Joi.string().hex().length(24)).max(5).optional().messages({
        'array.max': 'Maximum of 5 related products allowed'
    }),
    seller: Joi.forbidden(), // Seller should not be updated via this endpoint
    status: Joi.string().valid("approved", "rejected", "pending", "draft", "outOfStock").optional()
}).min(1); // At least one field must be provided for update

export function validateCreateProduct(data: Object) {
    return createProductSchema.validate(data, { abortEarly: false });
}

export function validateUpdateProduct(data: Object) {
    return updateProductSchema.validate(data, { abortEarly: false });
}

export function validateProductReview(data: Object) {
    return productReviewSchema.validate(data, { abortEarly: false });
}
